actor Новый_пользователь
actor Система_поддержки_клиентов

rectangle Система {
  usecase "Сбор анкетных данных" as UC1
  usecase "Формирование учётной записи" as UC2
  usecase "Подача заявки на проверку и регистрацию" as UC3
  usecase "Проверка заявки" as UC4
  usecase "Регистрация нового пользователя" as UC5
}

Новый_пользователь -- UC1
Новый_пользователь -- UC2
Новый_пользователь -- UC3
Новый_пользователь -- UC4
Новый_пользователь -- UC5

Система_поддержки_клиентов -- UC1
Система_поддержки_клиентов -- UC2
Система_поддержки_клиентов -- UC3
Система_поддержки_клиентов -- UC4
Система_поддержки_клиентов -- UC5

UC1 .u.> UC2 : <<include>>
UC2 .u.> UC3 : <<include>>
UC3 .u.> UC4 : <<include>>
UC4 .u.> UC5 : <<include>>

' Альтернативные потоки
usecase "Неверная информация" as UC6
usecase "Недостаточно данных" as UC7
usecase "Ошибка при регистрации" as UC8

Новый_пользователь -- UC6
Новый_пользователь -- UC7
Новый_пользователь -- UC8

UC1 .u.> UC6 : <<extend>>
UC2 .u.> UC7 : <<extend>>
UC3 .u.> UC8 : <<extend>>
