actor Специалист_службы_поддержки_клиентов
actor Пользователь_банка

rectangle Система {
  usecase "Проверка фактов по обращениям пользователей" as UC1
  usecase "Техническая поддержка" as UC2
  usecase "Консультирование по финансовым продуктам" as UC3
  usecase "Принятие мер в неотложных ситуациях" as UC4
}

Специалист_службы_поддержки_клиентов -- UC1
Специалист_службы_поддержки_клиентов -- UC2
Специалист_службы_поддержки_клиентов -- UC3
Специалист_службы_поддержки_клиентов -- UC4

Пользователь_банка -- UC1
Пользователь_банка -- UC2
Пользователь_банка -- UC3
Пользователь_банка -- UC4

UC1 .u.> UC2 : <<include>>
UC2 .u.> UC3 : <<include>>
UC3 .u.> UC4 : <<include>>

' Альтернативные потоки
usecase "Невозможно решить проблему" as UC5
usecase "Требуется дополнительная информация" as UC6

Специалист_службы_поддержки_клиентов -- UC5
Специалист_службы_поддержки_клиентов -- UC6

UC1 .u.> UC5 : <<extend>>
UC2 .u.> UC6 : <<extend>>
