actor Администратор_информационной_системы
actor Пользователь_банка

rectangle Система {
  usecase "Настройка полномочий" as UC1
  usecase "Распределение полномочий" as UC2
  usecase "Контроль целостности и резервирование данных" as UC3
  usecase "Мониторинг процессов" as UC4
}

Администратор_информационной_системы -- UC1
Администратор_информационной_системы -- UC2
Администратор_информационной_системы -- UC3
Администратор_информационной_системы -- UC4

Пользователь_банка -- UC1
Пользователь_банка -- UC2
Пользователь_банка -- UC3
Пользователь_банка -- UC4

UC1 .u.> UC2 : <<include>>
UC2 .u.> UC3 : <<include>>
UC3 .u.> UC4 : <<include>>

' Альтернативные потоки
usecase "Невозможно настроить полномочия" as UC5
usecase "Требуется дополнительная информация" as UC6

Администратор_информационной_системы -- UC5
Администратор_информационной_системы -- UC6

UC1 .u.> UC5 : <<extend>>
UC2 .u.> UC6 : <<extend>>
