actor Клиент_брокера
actor Брокер

rectangle Система {
  usecase "Формирование заявки на сделку" as UC1
  usecase "Регистрация заявки на сделку" as UC2
  usecase "Передача заявки на сделку" as UC3
  usecase "Фиксация записей о сделках" as UC4
}

Клиент_брокера -- UC1
Клиент_брокера -- UC2
Клиент_брокера -- UC3
Клиент_брокера -- UC4

Брокер -- UC1
Брокер -- UC2
Брокер -- UC3
Брокер -- UC4

UC1 .u.> UC2 : <<include>>
UC2 .u.> UC3 : <<include>>
UC3 .u.> UC4 : <<include>>

' Альтернативные потоки
usecase "Невозможно формировать заявку на сделку" as UC5
usecase "Требуется дополнительная информация" as UC6

Клиент_брокера -- UC5
Клиент_брокера -- UC6

UC1 .u.> UC5 : <<extend>>
UC2 .u.> UC6 : <<extend>>
