actor Кредитная_система
actor Клиент_банка
actor Банковский_служащий

rectangle Система {
  usecase "Предупреждение клиентов о предстоящих платежах" as UC1
  usecase "Контроль поступления платежей" as UC2
  usecase "Работа с просроченной задолженностью" as UC3
  usecase "Управление кредитными продуктами" as UC4
  usecase "Управление клиентскими данными" as UC5
}

Кредитная_система -- UC1
Кредитная_система -- UC2
Кредитная_система -- UC3
Кредитная_система -- UC4
Кредитная_система -- UC5

Клиент_банка -- UC1
Клиент_банка -- UC2
Клиент_банка -- UC3
Клиент_банка -- UC4
Клиент_банка -- UC5

Банковский_служащий -- UC1
Банковский_служащий -- UC2
Банковский_служащий -- UC3
Банковский_служащий -- UC4
Банковский_служащий -- UC5

UC1 .u.> UC2 : <<include>>
UC2 .u.> UC3 : <<include>>
UC3 .u.> UC4 : <<include>>
UC4 .u.> UC5 : <<include>>

' Альтернативные потоки
usecase "Невозможно предупредить клиента о предстоящем платеже" as UC6
usecase "Невозможно контролировать поступление платежей" as UC7
usecase "Невозможно работать с просроченной задолженностью" as UC8
usecase "Невозможно управлять кредитными продуктами" as UC9
usecase "Невозможно управлять клиентскими данными" as UC10

Кредитная_система -- UC6
Кредитная_система -- UC7
Кредитная_система -- UC8
Кредитная_система -- UC9
Кредитная_система -- UC10

UC1 .u.> UC6 : <<extend>>
UC2 .u.> UC7 : <<extend>>
UC3 .u.> UC8 : <<extend>>
UC4 .u.> UC9 : <<extend>>
UC5 .u.> UC10 : <<extend>>
