actor Пользователь_банкомата
actor Банковский_служащий
actor Система_безопасности

rectangle Система {
  usecase "Авторизация" as UC1
  usecase "Проверка счёта" as UC2
  usecase "Внесение наличных денежных средств" as UC3
  usecase "Снятие наличных денежных средств" as UC4
  usecase "Осуществление платежей" as UC5
  usecase "Осуществление переводов" as UC6
}

Пользователь_банкомата -- UC1
Пользователь_банкомата -- UC2
Пользователь_банкомата -- UC3
Пользователь_банкомата -- UC4
Пользователь_банкомата -- UC5
Пользователь_банкомата -- UC6

Банковский_служащий -- UC1
Банковский_служащий -- UC2
Банковский_служащий -- UC3
Банковский_служащий -- UC4
Банковский_служащий -- UC5
Банковский_служащий -- UC6

Система_безопасности -- UC1
Система_безопасности -- UC2
Система_безопасности -- UC3
Система_безопасности -- UC4
Система_безопасности -- UC5
Система_безопасности -- UC6

UC1 .u.> UC2 : <<include>>
UC2 .u.> UC3 : <<include>>
UC3 .u.> UC4 : <<include>>
UC4 .u.> UC5 : <<include>>
UC5 .u.> UC6 : <<include>>

' Альтернативные потоки
usecase "Невозможно авторизоваться" as UC7
usecase "Невозможно проверить счёт" as UC8
usecase "Невозможно внести наличные денежные средства" as UC9
usecase "Невозможно снять наличные денежные средства" as UC10
usecase "Невозможно осуществить платеж" as UC11
usecase "Невозможно осуществить перевод" as UC12

Пользователь_банкомата -- UC7
Пользователь_банкомата -- UC8
Пользователь_банкомата -- UC9
Пользователь_банкомата -- UC10
Пользователь_банкомата -- UC11
Пользователь_банкомата -- UC12

UC1 .u.> UC7 : <<extend>>
UC2 .u.> UC8 : <<extend>>
UC3 .u.> UC9 : <<extend>>
UC4 .u.> UC10 : <<extend>>
UC5 .u.> UC11 : <<extend>>
UC6 .u.> UC12 : <<extend>>
