@startuml 75
[*] --> New
New --> Checking : EvNew
Checking --> Approved : EvApproved
Checking --> Rejected : EvRejected
Checking --> OnHold : EvOnHold
Approved --> Opened : EvOpened
Rejected --> Closed : EvClosed
OnHold --> Checking : EvResume
OnHold --> Rejected : EvRejected
Opened --> Active : EvActivated
Active --> Inactive : EvDeactivated
Inactive --> Closed : EvClosed
Active --> Blocked : EvBlocked
Blocked --> Active : EvUnblocked
Blocked --> Closed : EvClosed

note left of New : Новая заявка
note right of Checking : Проверка критериев
note top of Approved : Заявка одобрена
note bottom of Rejected : Заявка отклонена
note left of Opened : Вклад открыт
note right of Active : Вклад активен
note top of Inactive : Вклад неактивен
note bottom of Closed : Вклад закрыт
note left of OnHold : Заявка на рассмотрении
note right of Blocked : Вклад заблокирован

@enduml
