@startuml
title "Покупка ценных монет или металлических слитков на сайте банка"

start
:Формирование заявки;
if (Доступна инвестиционная единица?) then (Да)
  :Ввод платежных реквизитов;
  :Проведение платежа;
  if (Платеж успешен?) then (Да)
    :Формирование подтверждения;
    :Подписание договора;
    :Отправка уведомлений;
    if (Выбран пункт выдачи?) then (Да)
      :Направление в пункт выдачи;
    else (Нет)
      :Заявка на пересылку;
    endif
  else (Нет)
    :Отмена платежа;
  endif
else (Нет)
  :Отмена заявки;
endif

@enduml
